# Laboratory Task 5 — PyTorch Basics

This notebook completes **Laboratory Task 5** from `02_PyTorch Basics.ipynb`.

The solution follows the task instructions step by step and includes outputs that make each result easy to verify.


## 1. Perform Standard Imports


In [1]:
import numpy as np
import torch

print("NumPy version:", np.__version__)
print("PyTorch version:", torch.__version__)


NumPy version: 2.3.5
PyTorch version: 2.10.0+cpu


## 2. Create `set_seed(seed: int)`

The function sets the random seed for both NumPy and PyTorch and does not return a value.


In [2]:
def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)


## 3. Create NumPy array `arr`

Create 6 random integers from **0 (inclusive) to 5 (exclusive)** using seed `42`.

`dtype=np.int32` is used so that Task 5 can explicitly change the tensor from `int32` to `int64`.


In [3]:
set_seed(42)

arr = np.random.randint(0, 5, size=6).astype(np.int32)

print("arr =", arr)
print("arr dtype =", arr.dtype)


arr = [3 4 2 4 4 1]
arr dtype = int32


## 4. Create tensor `x` from `arr`


In [4]:
x = torch.from_numpy(arr)

print("x =", x)
print("x dtype =", x.dtype)


x = tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
x dtype = torch.int32


## 5. Change `x` from `int32` to `int64`


In [5]:
x = x.type(torch.int64)

print("x =", x)
print("New dtype =", x.dtype)


x = tensor([3, 4, 2, 4, 4, 1])
New dtype = torch.int64


## 6. Reshape `x` into a 3 × 2 tensor


In [6]:
x = x.reshape(3, 2)

print("x =")
print(x)
print("Shape =", x.shape)


x =
tensor([[3, 4],
        [2, 4],
        [4, 1]])
Shape = torch.Size([3, 2])


## 7. Return the right-hand column of `x`


In [7]:
right_column = x[:, 1]

print("Right-hand column:")
print(right_column)


Right-hand column:
tensor([4, 4, 1])


## 8. Return the square values of `x` without changing `x`

`x ** 2` creates a new tensor, so the original `x` remains unchanged.


In [8]:
x_squared = x ** 2

print("Squared values:")
print(x_squared)

print("\nOriginal x is unchanged:")
print(x)


Squared values:
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

Original x is unchanged:
tensor([[3, 4],
        [2, 4],
        [4, 1]])


## 9. Create tensor `y`

Since `x` has shape **(3, 2)**, `y` must have **2 rows** for matrix multiplication.

To give `y` the same number of elements as `x` (6 elements), its shape is **(2, 3)**.


In [9]:
torch.manual_seed(42)

y = torch.randint(0, 5, (2, 3))

print("y =")
print(y)
print("Shape =", y.shape)
print("Number of elements =", y.numel())


y =
tensor([[2, 2, 1],
        [4, 1, 0]])
Shape = torch.Size([2, 3])
Number of elements = 6


## 10. Find the matrix product of `x` and `y`

`x` has shape **(3, 2)** and `y` has shape **(2, 3)**, so the resulting matrix has shape **(3, 3)**.


In [10]:
matrix_product = x @ y

print("x =")
print(x)

print("\ny =")
print(y)

print("\nx @ y =")
print(matrix_product)

print("\nProduct shape =", matrix_product.shape)


x =
tensor([[3, 4],
        [2, 4],
        [4, 1]])

y =
tensor([[2, 2, 1],
        [4, 1, 0]])

x @ y =
tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

Product shape = torch.Size([3, 3])


## Final Check

The completed notebook satisfies all 10 requirements of Laboratory Task 5:
- NumPy and PyTorch imported
- reusable `set_seed()` function created
- seeded NumPy random array created
- NumPy array converted to a PyTorch tensor
- dtype changed to `int64`
- tensor reshaped to 3 × 2
- right-hand column extracted
- squared tensor returned without modifying `x`
- compatible 2 × 3 tensor `y` created using PyTorch
- matrix product calculated
